-- Insert default pages
INSERT INTO pages (slug, title, subtitle, content, published) VALUES
('home', 'Home', 'Where elegance meets essence', '{"hero": {"title": "SERENA VENTUS", "subtitle": "Where elegance meets essence. Discover fragrances that capture the whispers of wind and the serenity of nature."}}', true),
('about', 'About', 'Discover the story behind Serena Ventus', '{"story": {"title": "OUR STORY", "content": "Founded in 2018, Serena Ventus emerged from a passion for capturing the ephemeral beauty of nature''s most delicate moments."}}', true),
('collection', 'Collection', 'Discover our signature fragrances', '{"intro": {"title": "SIGNATURE FRAGRANCES", "subtitle": "Six distinct compositions, each capturing a different facet of nature''s beauty"}}', true),
('contact', 'Contact', 'Connect with us for personalized consultations', '{"info": {"title": "GET IN TOUCH", "description": "Whether you''re seeking a signature scent, have questions about our collection, or wish to schedule a private consultation, we''re here to guide you on your olfactory journey."}}', true);

-- Insert products
INSERT INTO products (name, slug, description, long_description, price, size, notes, featured, published, sort_order) VALUES
('AURORA', 'aurora', 'A delicate blend of morning dew and jasmine petals, capturing the first light of dawn', 'Aurora opens with sparkling bergamot and fresh morning dew, transitioning into a heart of white jasmine and lily of the valley. The base of sandalwood and white musk creates a serene, luminous finish that lingers like the memory of a perfect sunrise.', 180.00, '50ml', '{"top": ["Bergamot", "Morning Dew", "Pink Grapefruit"], "heart": ["White Jasmine", "Lily of the Valley", "Peony"], "base": ["Sandalwood", "White Musk", "Blonde Woods"]}', true, true, 1),
('NOCTURNE', 'nocturne', 'Deep and mysterious, like moonlight dancing on still water', 'Nocturne begins with the dark richness of black currant and bergamot, evolving into an intoxicating bouquet of Bulgarian rose and violet. The base reveals warm amber, vanilla, and precious woods, creating an enigmatic fragrance perfect for evening wear.', 195.00, '50ml', '{"top": ["Black Currant", "Bergamot", "Pink Pepper"], "heart": ["Bulgarian Rose", "Violet", "Iris"], "base": ["Amber", "Vanilla", "Precious Woods"]}', true, true, 2),
('ZEPHYR', 'zephyr', 'Light and airy, capturing the essence of gentle summer breezes', 'Zephyr embodies the carefree spirit of summer with its fresh citrus opening of lemon and mandarin. The heart blooms with delicate florals including lily of the valley and freesia, while the base of white musk and cedar provides an clean, airy finish.', 165.00, '50ml', '{"top": ["Lemon", "Mandarin", "Green Leaves"], "heart": ["Lily of the Valley", "Freesia", "White Tea"], "base": ["White Musk", "Cedar", "Soft Amber"]}', true, true, 3),
('SOLSTICE', 'solstice', 'A warm embrace of golden hour, where earth meets sky', 'Solstice captures the magic of the longest day with warm spices and golden florals. Opening with cardamom and orange blossom, it reveals a heart of tuberose and ylang-ylang, grounded by a base of sandalwood, benzoin, and soft vanilla.', 210.00, '50ml', '{"top": ["Cardamom", "Orange Blossom", "Mandarin"], "heart": ["Tuberose", "Ylang-Ylang", "Magnolia"], "base": ["Sandalwood", "Benzoin", "Soft Vanilla"]}', false, true, 4),
('TEMPEST', 'tempest', 'The raw power of nature, captured in crystalline clarity', 'Tempest evokes the electric energy before a storm with its bold opening of sea salt and ozonic notes. The heart reveals stormy florals like iris and cyclamen, while the base of driftwood, ambergris, and mineral musk creates a powerful, unforgettable presence.', 225.00, '50ml', '{"top": ["Sea Salt", "Ozonic Notes", "Bergamot"], "heart": ["Iris", "Cyclamen", "Water Lily"], "base": ["Driftwood", "Ambergris", "Mineral Musk"]}', false, true, 5),
('REVERIE', 'reverie', 'A dreamy composition that blurs the line between reality and imagination', 'Reverie transports you to a world of dreams with its ethereal blend of soft florals and powdery musks. Opening with delicate pear and pink pepper, it unfolds into a heart of peony and cashmere wood, finishing with a cloud-like base of white musk and soft vanilla.', 185.00, '50ml', '{"top": ["Pear", "Pink Pepper", "Aldehydes"], "heart": ["Peony", "Cashmere Wood", "Rose Petals"], "base": ["White Musk", "Soft Vanilla", "Powdery Notes"]}', false, true, 6);
